kind: Deployment
apiVersion: apps/v1
metadata:
  name: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: zero2onebase2/todoreactimage


...
apiVersion: v1
kind: Service
metadata:
  name: react-srv
spec:
  type: NodePort
  selector:
    app: react
  ports:
    - name: my-app
      port: 3000
      targetPort: 3000

